/**
 * KEV — portfolio data.
 * Derived from web media in PORTAFOLIO/web (see lib/media-manifest.json,
 * generated by scripts/process-media.sh + manifest step).
 *
 * EDITABLE: títulos, clientes, años y blurbs son provisionales — ajustar aquí.
 */
import manifestJson from './media-manifest.json'

export type MediaItem = {
  src: string
  type: 'image' | 'video'
  poster?: string
  w: number
  h: number
  /** seconds — videos only */
  duration?: number
}

export type ProjectKind = 'Photography' | 'Video' | 'Brand'

export type Project = {
  slug: string
  title: string
  client: string
  year: string
  kind: ProjectKind
  blurb?: string
  /** index hover preview + cover */
  cover: MediaItem
  items: MediaItem[]
}

const manifest = manifestJson as Record<string, number[]>

const natural = (a: string, b: string) =>
  a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' })

function photoItems(prefix: string): MediaItem[] {
  return Object.keys(manifest)
    .filter(
      (p) =>
        p.startsWith(prefix + '/') &&
        p.endsWith('.jpg') &&
        !p.endsWith('-poster.jpg'),
    )
    .sort(natural)
    .map((p) => {
      const [w, h] = manifest[p]
      return { src: p, type: 'image' as const, w, h }
    })
}

function videoItem(path: string): MediaItem {
  const entry = manifest[path]
  if (!entry) throw new Error(`Media not in manifest: ${path}`)
  const [w, h, duration] = entry
  const poster = path.replace(/\.mp4$/, '-poster.jpg')
  return {
    src: path,
    type: 'video',
    poster: manifest[poster] ? poster : undefined,
    w,
    h,
    duration,
  }
}

function photoProject(p: {
  slug: string
  title: string
  client: string
  year: string
  kind?: ProjectKind
  dir: string
  blurb?: string
}): Project {
  const items = photoItems(p.dir)
  // fail at build time (generateStaticParams) instead of rendering a broken page
  if (items.length === 0)
    throw new Error(`No media found in manifest for project dir: ${p.dir}`)
  return {
    slug: p.slug,
    title: p.title,
    client: p.client,
    year: p.year,
    kind: p.kind ?? 'Photography',
    blurb: p.blurb,
    cover: items[0],
    items,
  }
}

function videoProject(p: {
  slug: string
  title: string
  client: string
  year: string
  kind?: ProjectKind
  src: string
  blurb?: string
}): Project {
  const item = videoItem(p.src)
  return {
    slug: p.slug,
    title: p.title,
    client: p.client,
    year: p.year,
    kind: p.kind ?? 'Video',
    blurb: p.blurb,
    cover: item,
    items: [item],
  }
}

export const projects: Project[] = [
  /* ---- Photography ---- */
  photoProject({
    slug: 'j-balvin',
    title: 'J Balvin',
    client: 'J Balvin',
    year: '2025',
    dir: 'artistas/balvin',
  }),
  photoProject({
    slug: 'maluma-x-maisak',
    title: 'Maluma × Maisak',
    client: 'Maluma',
    year: '2025',
    dir: 'artistas/maluma-x-maisak',
  }),
  photoProject({
    slug: 'maisak-shooting',
    title: 'Maisak — Shooting',
    client: 'Maisak',
    year: '2024',
    dir: 'artistas/shooting-maisak',
  }),
  photoProject({
    slug: 'fdrs',
    title: 'FDRS',
    client: 'FDRS',
    year: '2024',
    dir: 'artistas/fdrs',
  }),
  photoProject({
    slug: 'kev-x-new-era',
    title: 'Kev × New Era',
    client: 'New Era',
    year: '2025',
    kind: 'Brand',
    dir: 'marcas/kev-x-new-era',
  }),

  /* ---- Video clips ---- */
  videoProject({
    slug: 'en-otra-vida',
    title: 'En Otra Vida',
    client: 'Music Video',
    year: '2025',
    src: 'video-clips/en-otra-vida-final-pro-res.mp4',
  }),
  videoProject({
    slug: 'la-esencia',
    title: 'La Esencia',
    client: 'Music Video',
    year: '2025',
    src: 'video-clips/la-esencia-mp4.mp4',
  }),
  videoProject({
    slug: 'tikiti',
    title: 'Tikiti',
    client: 'Music Video',
    year: '2024',
    src: 'video-clips/tikiti-redes.mp4',
  }),
  videoProject({
    slug: 'no-es-un-secreto',
    title: 'No Es Un Secreto',
    client: 'Music Video',
    year: '2024',
    src: 'video-clips/no-es-un-secreto-redes.mp4',
  }),
  videoProject({
    slug: 'create-ovy-madrid',
    title: 'Create — OVY Madrid',
    client: 'OVY On The Drums',
    year: '2024',
    src: 'video-clips/create-ovy-madrid.mp4',
  }),
  videoProject({
    slug: 'up-bts',
    title: 'UP+ — Behind The Scenes',
    client: 'UP+',
    year: '2024',
    src: 'video-clips/bts-up-mp44.mp4',
  }),
  videoProject({
    slug: 'showreel',
    title: 'Showreel',
    client: 'KEV',
    year: '2025',
    src: 'video-clips/reel-kev.mp4',
  }),

  /* ---- Brand films ---- */
  videoProject({
    slug: 'mood-lab',
    title: 'Mood Lab',
    client: 'Mood Lab',
    year: '2025',
    kind: 'Brand',
    src: 'marcas/mood-lab/mood-lab-ig.mp4',
  }),
  videoProject({
    slug: 'blouw-up',
    title: 'Blouw Up',
    client: 'Blouw Up',
    year: '2024',
    kind: 'Brand',
    src: 'marcas/blouw-up.mp4',
  }),
  videoProject({
    slug: 'moda-cosmos',
    title: 'Moda Cosmos',
    client: 'Moda Cosmos',
    year: '2024',
    kind: 'Brand',
    src: 'marcas/moda-cosmos.mp4',
  }),
]

export const projectBySlug = (slug: string): Project | undefined =>
  projects.find((p) => p.slug === slug)

export const nextProject = (slug: string): Project => {
  const i = projects.findIndex((p) => p.slug === slug)
  return projects[(i + 1) % projects.length]
}

export const videoProjects = projects.filter(
  (p) => p.items[0]?.type === 'video',
)

export const info = {
  bio: 'KEV is a photographer and music-video director. The work moves between Latin music culture and fashion editorial — campaigns, album cycles, music videos and brand collaborations.',
  clients: ['J Balvin', 'Maluma', 'Maisak', 'FDRS', 'New Era', 'OVY On The Drums', 'Mood Lab'],
  services: ['Photography', 'Music Video Direction', 'Brand Film', 'Creative Direction'],
  contact: [
    { label: 'Email', value: 'studio@kev.com' },
    { label: 'Instagram', value: '@kev' },
  ],
}
